FLAGS = -ansi -Wall -Wextra -Werror -pedantic-errors -lm

symnmf: symnmf.c
	gcc -o symnmf.c $(FLAGS)
	
module: symnmfmodule.c setup.py
	python3 setup.py build_ext --inplace

clean:
	rm -f *.o
	rm -rf build